#!/bin/bash
# SubSynco - a tool for synchronizing subtitle files
# Copyright (C) 2015  da-mkay
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


SCRIPT_DIR=$(dirname `which $0`)
SRC_DIR="$SCRIPT_DIR/../../src"
LOCALE_DIR="$SRC_DIR/subsynco/data/locale"

touch $LOCALE_DIR/subsynco.pot
xgettext -j -p $LOCALE_DIR/ -o subsynco.pot -L Python $SRC_DIR/subsynco-gtk
find $SRC_DIR -type f -iname "*.py" | xgettext -j -p $LOCALE_DIR/ -o subsynco.pot -f -
find $SRC_DIR -type f -iname "*.glade" | xgettext -j -p $LOCALE_DIR/ -o subsynco.pot -f -

